### ISSUE TITLE
Negative number invalid for list

### ISSUE THREAD

**Issue by schotime** [adams85/bundling#15]
We tried upgrading to 3.5 but received a negative number error on List creation. It was spawned from this method. I'm assuming 0 items come back which then results in -1.

https://github.com/adams85/bundling/blob/a630f8a7062c19c5edb2ffd7b7f4d2df758a240f/source/Bundling/Internal/Rendering/SourceIncludesBundleHtmlRenderer.cs#L61

**Comment by adams85** [comment]
Your assumption is correct.

v3.5.1 addresses the issue. It's already available on NuGet.
