### ISSUE TITLE
Cannot access node_modules folder

### ISSUE THREAD

**Issue by samwx** [adams85/bundling#3]
Hi everyone!

I'm trying to import scss file from `node_modules` in `wwwroot/scss` and I'm getting this error:

```
[13:28:55 Warning] Karambolo.AspNetCore.Bundling.Sass.SassCompiler
Sass compilation of '/scss/main.scss' failed.
Error: File to import not found or unreadable: ../../node_modules/blip-toolkit/dist/scss/variables/module.scss.
        on line 1 of scss/main.scss
>> @import "../../node_modules/blip-toolkit/dist/scss/variables/module.scss";
```

I've checked if path is correct and it is. Can anyone tell me if this package has some restriction to import scss files from `node_modules`?

Thanks!

**Comment by adams85** [comment]
Hi!

There's no such restriction.

I suspect the node_modules directory is located outside of the root directory of the file provider which is used to gather source files.

This file provider can be set through the BundlingOptions.SourceFileProvider property when calling UseBundling in Startup.Configure. If not set, IHostingEnvironment.WebRootFileProvider is used by default whose root folder is your web root directory (wwwroot).

Could you verify that your node_modules directory is within the SourceFileProvider's root folder?
