### ISSUE TITLE
.Net Core 3 issues

### ISSUE THREAD

**Issue by lee-baker** [adams85/bundling#6]
I am converting an older project from Asp.Net MVC 4 and found your library. I figured I would go straight with .net core 3 however there have been a couple of issues.

Microsft has deprecated the IHostingEnvironment in favour of IWebHostEnvironment. This means the UseDefaults extension method doesn't work.
Also, when running the project I get a method not found exception
Method not found: 'Void Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware

Let me know if I can provide more info.

Thanks

**Comment by adams85** [comment]
Hi!

`UseDefaults` is not essential, you can do the same configuration manually that it does under the hood. See https://github.com/adams85/bundling/blob/master/source/Bundling/BundlingConfigurerExtensions.cs#L168

Retargeting to NET Core 3 and rebuilding the project may solve the method-not-found issue, but it can be more complicated.

Perhaps I can spare some time for this in the following days but I make no promises. If it's crucial for you, you can provide a PR resolving this and I will release it as a preview package.

**Comment by adams85** [comment]
Good news! As I expected, it was a bit tricker than a simple rebuild, but finally I could make it work with Preview 7: https://www.nuget.org/packages/Karambolo.AspNetCore.Bundling/3.0.0-pre1

As a bonus, I get rid of the Newtonsoft.Json dependency by replacing it with System.Text.Json.

However, design time bundling seems broken. It has some issues which I don't have time for to track down right now.
